// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-python     v0.25.0  (commit 293fdc02038ee2bf0e2e206711b69c90ac0d413f)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-python.git
// Toolchain versions: see image labels (docker inspect).

package bonsaipython

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 8
