// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-javascript v0.25.0  (commit 44c892e0be055ac465d5eeddae6d3e194424e7de)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-javascript.git
// Toolchain versions: see image labels (docker inspect).

package bonsaijavascript

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 7

// GrammarVersion is the upstream grammar ref (tag or branch) this
// module's parser was generated from. The exact commit is in the
// header above.
const GrammarVersion = "v0.25.0"

// TreeSitterVersion is the tree-sitter runtime ref whose compiled
// form this module embeds.
const TreeSitterVersion = "v0.25.10"
