// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-bash       v0.25.1  (commit a06c2e4415e9bc0346c6b86d401879ffb44058f7)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-bash.git
// Toolchain versions: see image labels (docker inspect).

package bonsaibash

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 20
