// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-ruby       v0.23.1  (commit 71bd32fb7607035768799732addba884a37a6210)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-ruby.git
// Toolchain versions: see image labels (docker inspect).

package bonsairuby

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 33

// GrammarVersion is the upstream grammar ref (tag or branch) this
// module's parser was generated from. The exact commit is in the
// header above.
const GrammarVersion = "v0.23.1"

// TreeSitterVersion is the tree-sitter runtime ref whose compiled
// form this module embeds.
const TreeSitterVersion = "v0.25.10"
