// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-yaml v0.7.2 (src/node-types.json).

package bonsaiyaml

// KindX constants name every named, visible node type this grammar can
// produce as Node.Kind. Values are the raw tree-sitter kind strings, so
// they work anywhere a node kind string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindAlias              = "alias"
	KindAliasName          = "alias_name"
	KindAnchor             = "anchor"
	KindAnchorName         = "anchor_name"
	KindBlockMapping       = "block_mapping"
	KindBlockMappingPair   = "block_mapping_pair"
	KindBlockNode          = "block_node"
	KindBlockScalar        = "block_scalar"
	KindBlockSequence      = "block_sequence"
	KindBlockSequenceItem  = "block_sequence_item"
	KindBooleanScalar      = "boolean_scalar"
	KindComment            = "comment"
	KindDirectiveName      = "directive_name"
	KindDirectiveParameter = "directive_parameter"
	KindDocument           = "document"
	KindDoubleQuoteScalar  = "double_quote_scalar"
	KindEscapeSequence     = "escape_sequence"
	KindFloatScalar        = "float_scalar"
	KindFlowMapping        = "flow_mapping"
	KindFlowNode           = "flow_node"
	KindFlowPair           = "flow_pair"
	KindFlowSequence       = "flow_sequence"
	KindIntegerScalar      = "integer_scalar"
	KindNullScalar         = "null_scalar"
	KindPlainScalar        = "plain_scalar"
	KindReservedDirective  = "reserved_directive"
	KindSingleQuoteScalar  = "single_quote_scalar"
	KindStream             = "stream"
	KindStringScalar       = "string_scalar"
	KindTag                = "tag"
	KindTagDirective       = "tag_directive"
	KindTagHandle          = "tag_handle"
	KindTagPrefix          = "tag_prefix"
	KindTimestampScalar    = "timestamp_scalar"
	KindYamlDirective      = "yaml_directive"
	KindYamlVersion        = "yaml_version"
)

// FieldX constants name every field this grammar attaches to child
// nodes, for Node.ChildByField and Node.Field.
const (
	FieldKey   = "key"
	FieldValue = "value"
)
