// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-yaml       v0.7.2  (commit 7708026449bed86239b1cd5bce6e3c34dbca6415)
//
// Grammar source:     https://github.com/tree-sitter-grammars/tree-sitter-yaml.git
// Toolchain versions: see image labels (docker inspect).

package bonsaiyaml

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 4
