// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-markdown v0.5.3 (src/node-types.json).

package bonsaimarkdown

// KindX constants name every named, visible node type this grammar can
// produce as Node.Type. Values are the raw tree-sitter kind strings, so
// they work anywhere a node type string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindAtxH1Marker               = "atx_h1_marker"
	KindAtxH2Marker               = "atx_h2_marker"
	KindAtxH3Marker               = "atx_h3_marker"
	KindAtxH4Marker               = "atx_h4_marker"
	KindAtxH5Marker               = "atx_h5_marker"
	KindAtxH6Marker               = "atx_h6_marker"
	KindAtxHeading                = "atx_heading"
	KindBackslashEscape           = "backslash_escape"
	KindBlockContinuation         = "block_continuation"
	KindBlockQuote                = "block_quote"
	KindBlockQuoteMarker          = "block_quote_marker"
	KindCodeFenceContent          = "code_fence_content"
	KindDocument                  = "document"
	KindEntityReference           = "entity_reference"
	KindFencedCodeBlock           = "fenced_code_block"
	KindFencedCodeBlockDelimiter  = "fenced_code_block_delimiter"
	KindHtmlBlock                 = "html_block"
	KindIndentedCodeBlock         = "indented_code_block"
	KindInfoString                = "info_string"
	KindInline                    = "inline"
	KindLanguage                  = "language"
	KindLinkDestination           = "link_destination"
	KindLinkLabel                 = "link_label"
	KindLinkReferenceDefinition   = "link_reference_definition"
	KindLinkTitle                 = "link_title"
	KindList                      = "list"
	KindListItem                  = "list_item"
	KindListMarkerDot             = "list_marker_dot"
	KindListMarkerMinus           = "list_marker_minus"
	KindListMarkerParenthesis     = "list_marker_parenthesis"
	KindListMarkerPlus            = "list_marker_plus"
	KindListMarkerStar            = "list_marker_star"
	KindMinusMetadata             = "minus_metadata"
	KindNumericCharacterReference = "numeric_character_reference"
	KindParagraph                 = "paragraph"
	KindPipeTable                 = "pipe_table"
	KindPipeTableAlignLeft        = "pipe_table_align_left"
	KindPipeTableAlignRight       = "pipe_table_align_right"
	KindPipeTableCell             = "pipe_table_cell"
	KindPipeTableDelimiterCell    = "pipe_table_delimiter_cell"
	KindPipeTableDelimiterRow     = "pipe_table_delimiter_row"
	KindPipeTableHeader           = "pipe_table_header"
	KindPipeTableRow              = "pipe_table_row"
	KindPlusMetadata              = "plus_metadata"
	KindSection                   = "section"
	KindSetextH1Underline         = "setext_h1_underline"
	KindSetextH2Underline         = "setext_h2_underline"
	KindSetextHeading             = "setext_heading"
	KindTaskListMarkerChecked     = "task_list_marker_checked"
	KindTaskListMarkerUnchecked   = "task_list_marker_unchecked"
	KindThematicBreak             = "thematic_break"
)

// FieldX constants name every field this grammar attaches to child
// nodes, for Node.ChildByField and Node.Field.
const (
	FieldHeadingContent = "heading_content"
)
