// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-dockerfile v0.2.0 (src/node-types.json).

package bonsaidockerfile

// KindX constants name every named, visible node type this grammar can
// produce as Node.Kind. Values are the raw tree-sitter kind strings, so
// they work anywhere a node kind string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindAddInstruction         = "add_instruction"
	KindArgInstruction         = "arg_instruction"
	KindCmdInstruction         = "cmd_instruction"
	KindComment                = "comment"
	KindCopyInstruction        = "copy_instruction"
	KindCrossBuildInstruction  = "cross_build_instruction"
	KindDoubleQuotedString     = "double_quoted_string"
	KindEntrypointInstruction  = "entrypoint_instruction"
	KindEnvInstruction         = "env_instruction"
	KindEnvPair                = "env_pair"
	KindEscapeSequence         = "escape_sequence"
	KindExpansion              = "expansion"
	KindExposeInstruction      = "expose_instruction"
	KindExposePort             = "expose_port"
	KindFromInstruction        = "from_instruction"
	KindHealthcheckInstruction = "healthcheck_instruction"
	KindHeredocBlock           = "heredoc_block"
	KindHeredocEnd             = "heredoc_end"
	KindHeredocLine            = "heredoc_line"
	KindHeredocMarker          = "heredoc_marker"
	KindImageAlias             = "image_alias"
	KindImageDigest            = "image_digest"
	KindImageName              = "image_name"
	KindImageSpec              = "image_spec"
	KindImageTag               = "image_tag"
	KindJsonString             = "json_string"
	KindJsonStringArray        = "json_string_array"
	KindLabelInstruction       = "label_instruction"
	KindLabelPair              = "label_pair"
	KindLineContinuation       = "line_continuation"
	KindMaintainerInstruction  = "maintainer_instruction"
	KindMountParam             = "mount_param"
	KindMountParamParam        = "mount_param_param"
	KindOnbuildInstruction     = "onbuild_instruction"
	KindParam                  = "param"
	KindPath                   = "path"
	KindRunInstruction         = "run_instruction"
	KindShellCommand           = "shell_command"
	KindShellFragment          = "shell_fragment"
	KindShellInstruction       = "shell_instruction"
	KindSingleQuotedString     = "single_quoted_string"
	KindSourceFile             = "source_file"
	KindStopsignalInstruction  = "stopsignal_instruction"
	KindUnquotedString         = "unquoted_string"
	KindUserInstruction        = "user_instruction"
	KindVariable               = "variable"
	KindVolumeInstruction      = "volume_instruction"
	KindWorkdirInstruction     = "workdir_instruction"
)

// FieldX constants name every field this grammar attaches to child
// nodes, for Node.ChildByField and Node.Field.
const (
	FieldAs      = "as"
	FieldDefault = "default"
	FieldDigest  = "digest"
	FieldGroup   = "group"
	FieldKey     = "key"
	FieldName    = "name"
	FieldTag     = "tag"
	FieldUser    = "user"
	FieldValue   = "value"
)
