// Code generated by libc-gen. DO NOT EDIT.

package bonsaidockerfile

import "bytes"

func (m *Module) _memcmp(s1, s2, n int32) int32 {
	e1, e2 := s1+n, s2+n
	b1 := (*m.memory)[uint32(s1):uint32(e1)]
	b2 := (*m.memory)[uint32(s2):uint32(e2)]
	return int32(bytes.Compare(b1, b2))
}

func (m *Module) _strlen(s int32) int32 {
	return int32(bytes.IndexByte((*m.memory)[uint32(s):], 0))
}
