// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-dockerfile v0.2.0  (commit 868e44ce378deb68aac902a9db68ff82d2299dd0)
//
// Grammar source:     https://github.com/camdencheek/tree-sitter-dockerfile.git
// Toolchain versions: see image labels (docker inspect).

package bonsaidockerfile

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 2

// GrammarVersion is the upstream grammar ref (tag or branch) this
// module's parser was generated from. The exact commit is in the
// header above.
const GrammarVersion = "v0.2.0"

// TreeSitterVersion is the tree-sitter runtime ref whose compiled
// form this module embeds.
const TreeSitterVersion = "v0.25.10"
