// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-groovy     initial  (commit 781d9cd1b482a70a6b27091e5c9e14bbcab3b768)
//
// Grammar source:     https://github.com/murtaza64/tree-sitter-groovy.git
// Toolchain versions: see image labels (docker inspect).

package bonsaigroovy

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 14

// GrammarVersion is the upstream grammar ref (tag or branch) this
// module's parser was generated from. The exact commit is in the
// header above.
const GrammarVersion = "initial"

// TreeSitterVersion is the tree-sitter runtime ref whose compiled
// form this module embeds.
const TreeSitterVersion = "v0.25.10"
