// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-java       v0.23.5  (commit 94703d5a6bed02b98e438d7cad1136c01a60ba2c)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-java.git
// Toolchain versions: see image labels (docker inspect).

package bonsaijava

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 8

// GrammarVersion is the upstream grammar ref (tag or branch) this
// module's parser was generated from. The exact commit is in the
// header above.
const GrammarVersion = "v0.23.5"

// TreeSitterVersion is the tree-sitter runtime ref whose compiled
// form this module embeds.
const TreeSitterVersion = "v0.25.10"
