// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-markdown v0.5.3 (src/node-types.json).

package bonsaimarkdowninline

// KindX constants name every named, visible node type this grammar can
// produce as Node.Kind. Values are the raw tree-sitter kind strings, so
// they work anywhere a node kind string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindBackslashEscape           = "backslash_escape"
	KindCodeSpan                  = "code_span"
	KindCodeSpanDelimiter         = "code_span_delimiter"
	KindCollapsedReferenceLink    = "collapsed_reference_link"
	KindEmailAutolink             = "email_autolink"
	KindEmphasis                  = "emphasis"
	KindEmphasisDelimiter         = "emphasis_delimiter"
	KindEntityReference           = "entity_reference"
	KindFullReferenceLink         = "full_reference_link"
	KindHardLineBreak             = "hard_line_break"
	KindHtmlTag                   = "html_tag"
	KindImage                     = "image"
	KindImageDescription          = "image_description"
	KindInline                    = "inline"
	KindInlineLink                = "inline_link"
	KindLatexBlock                = "latex_block"
	KindLatexSpanDelimiter        = "latex_span_delimiter"
	KindLinkDestination           = "link_destination"
	KindLinkLabel                 = "link_label"
	KindLinkText                  = "link_text"
	KindLinkTitle                 = "link_title"
	KindNumericCharacterReference = "numeric_character_reference"
	KindShortcutLink              = "shortcut_link"
	KindStrikethrough             = "strikethrough"
	KindStrongEmphasis            = "strong_emphasis"
	KindUriAutolink               = "uri_autolink"
)
