// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-markdown   v0.5.3  (commit f969cd3ae3f9fbd4e43205431d0ae286014c05b5)
//
// Grammar source:     https://github.com/tree-sitter-grammars/tree-sitter-markdown.git
// Toolchain versions: see image labels (docker inspect).

package bonsaimarkdowninline

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 5
