// Code generated by bonsai-builder. DO NOT EDIT.
//
// Upstream license notices for the code compiled into this module.

package bonsaigo

import _ "embed"

// LicenseTreeSitter is the license of the tree-sitter runtime
// (v0.25.10) whose compiled form this package embeds.
//
//go:embed LICENSE.tree-sitter
var LicenseTreeSitter string

// LicenseGrammar is the license of the grammar
// (https://github.com/tree-sitter/tree-sitter-go.git @ v0.25.0)
// whose compiled form this package embeds.
//
//go:embed LICENSE.grammar
var LicenseGrammar string
