// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-go         v0.25.0  (commit 1547678a9da59885853f5f5cc8a99cc203fa2e2c)
//
// Grammar source:     https://github.com/tree-sitter/tree-sitter-go.git
// Toolchain versions: see image labels (docker inspect).

package bonsaigo

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 5
