// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-go-template master (src/node-types.json).

package bonsaigotemplate

// KindX constants name every named, visible node type this grammar can
// produce as Node.Kind. Values are the raw tree-sitter kind strings, so
// they work anywhere a node kind string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindArgumentList             = "argument_list"
	KindAssignment               = "assignment"
	KindBlockAction              = "block_action"
	KindBreakAction              = "break_action"
	KindChainedPipeline          = "chained_pipeline"
	KindComment                  = "comment"
	KindContinueAction           = "continue_action"
	KindDefineAction             = "define_action"
	KindDot                      = "dot"
	KindEscapeSequence           = "escape_sequence"
	KindFalse                    = "false"
	KindField                    = "field"
	KindFieldIdentifier          = "field_identifier"
	KindFloatLiteral             = "float_literal"
	KindFunctionCall             = "function_call"
	KindIdentifier               = "identifier"
	KindIfAction                 = "if_action"
	KindImaginaryLiteral         = "imaginary_literal"
	KindIntLiteral               = "int_literal"
	KindInterpretedStringLiteral = "interpreted_string_literal"
	KindMethodCall               = "method_call"
	KindNil                      = "nil"
	KindParenthesizedPipeline    = "parenthesized_pipeline"
	KindRangeAction              = "range_action"
	KindRangeVariableDefinition  = "range_variable_definition"
	KindRawStringLiteral         = "raw_string_literal"
	KindRuneLiteral              = "rune_literal"
	KindSelectorExpression       = "selector_expression"
	KindTemplate                 = "template"
	KindTemplateAction           = "template_action"
	KindText                     = "text"
	KindTrue                     = "true"
	KindVariable                 = "variable"
	KindVariableDefinition       = "variable_definition"
	KindWithAction               = "with_action"
	KindYamlNoInjectionText      = "yaml_no_injection_text"
)

// FieldX constants name every field this grammar attaches to child
// nodes, for Node.ChildByField and Node.Field.
const (
	FieldAlternative = "alternative"
	FieldArgument    = "argument"
	FieldArguments   = "arguments"
	FieldBody        = "body"
	FieldCondition   = "condition"
	FieldConsequence = "consequence"
	FieldElement     = "element"
	FieldField       = "field"
	FieldFunction    = "function"
	FieldIndex       = "index"
	FieldMethod      = "method"
	FieldName        = "name"
	FieldOperand     = "operand"
	FieldOption      = "option"
	FieldRange       = "range"
	FieldValue       = "value"
	FieldVariable    = "variable"
)
