// Code generated by bonsai-builder. DO NOT EDIT.
//
// Inputs (baked into image):
//   tree-sitter            v0.25.10  (commit da6fe9beb4f7f67beb75914ca8e0d48ae48d6406)
//   tree-sitter-go-template master  (commit aa71f63de226c5592dfbfc1f29949522d7c95fac)
//
// Grammar source:     https://github.com/ngalaiko/tree-sitter-go-template.git
// Toolchain versions: see image labels (docker inspect).

package bonsaigotemplate

// InitialPages is the wasm module's declared initial linear-memory size,
// in 64 KiB WebAssembly pages. Memory passed to New must already be sized
// to at least InitialPages * 65536 bytes before the call.
const InitialPages = 2
