// Code generated by bonsai-builder. DO NOT EDIT.
//
// Node kinds and field names from tree-sitter-hcl v1.2.0 (src/node-types.json).

package bonsaiterraform

// KindX constants name every named, visible node type this grammar can
// produce as Node.Kind. Values are the raw tree-sitter kind strings, so
// they work anywhere a node kind string is expected, like Node.Find.
// Anonymous tokens (keywords, punctuation) and supertypes have no
// constants.
const (
	KindAttrSplat                  = "attr_splat"
	KindAttribute                  = "attribute"
	KindBinaryOperation            = "binary_operation"
	KindBlock                      = "block"
	KindBlockEnd                   = "block_end"
	KindBlockStart                 = "block_start"
	KindBody                       = "body"
	KindBoolLit                    = "bool_lit"
	KindCollectionValue            = "collection_value"
	KindComment                    = "comment"
	KindConditional                = "conditional"
	KindConfigFile                 = "config_file"
	KindEllipsis                   = "ellipsis"
	KindExpression                 = "expression"
	KindForCond                    = "for_cond"
	KindForExpr                    = "for_expr"
	KindForIntro                   = "for_intro"
	KindForObjectExpr              = "for_object_expr"
	KindForTupleExpr               = "for_tuple_expr"
	KindFullSplat                  = "full_splat"
	KindFunctionArguments          = "function_arguments"
	KindFunctionCall               = "function_call"
	KindGetAttr                    = "get_attr"
	KindHeredocIdentifier          = "heredoc_identifier"
	KindHeredocStart               = "heredoc_start"
	KindHeredocTemplate            = "heredoc_template"
	KindIdentifier                 = "identifier"
	KindIndex                      = "index"
	KindLegacyIndex                = "legacy_index"
	KindLiteralValue               = "literal_value"
	KindNewIndex                   = "new_index"
	KindNullLit                    = "null_lit"
	KindNumericLit                 = "numeric_lit"
	KindObject                     = "object"
	KindObjectElem                 = "object_elem"
	KindObjectEnd                  = "object_end"
	KindObjectStart                = "object_start"
	KindOperation                  = "operation"
	KindQuotedTemplate             = "quoted_template"
	KindQuotedTemplateEnd          = "quoted_template_end"
	KindQuotedTemplateStart        = "quoted_template_start"
	KindSplat                      = "splat"
	KindStringLit                  = "string_lit"
	KindStripMarker                = "strip_marker"
	KindTemplateDirective          = "template_directive"
	KindTemplateDirectiveEnd       = "template_directive_end"
	KindTemplateDirectiveStart     = "template_directive_start"
	KindTemplateElseIntro          = "template_else_intro"
	KindTemplateExpr               = "template_expr"
	KindTemplateFor                = "template_for"
	KindTemplateForEnd             = "template_for_end"
	KindTemplateForStart           = "template_for_start"
	KindTemplateIf                 = "template_if"
	KindTemplateIfEnd              = "template_if_end"
	KindTemplateIfIntro            = "template_if_intro"
	KindTemplateInterpolation      = "template_interpolation"
	KindTemplateInterpolationEnd   = "template_interpolation_end"
	KindTemplateInterpolationStart = "template_interpolation_start"
	KindTemplateLiteral            = "template_literal"
	KindTuple                      = "tuple"
	KindTupleEnd                   = "tuple_end"
	KindTupleStart                 = "tuple_start"
	KindUnaryOperation             = "unary_operation"
	KindVariableExpr               = "variable_expr"
)

// FieldX constants name every field this grammar attaches to child
// nodes, for Node.ChildByField and Node.Field.
const (
	FieldKey = "key"
	FieldVal = "val"
)
